apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-api
  labels:
    app: fake-news
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fake-news
  template:
    metadata:
      labels:
        app: fake-news
    spec:
      containers:
      - name: api
        image: svrma13/fake-news-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: fake-news-secrets
              key: vault-token
        - name: JENKINS_USER
          valueFrom:
            secretKeyRef:
              name: fake-news-secrets
              key: jenkins-user
        - name: JENKINS_PASS
          valueFrom:
            secretKeyRef:
              name: fake-news-secrets
              key: jenkins-pass
        - name: JENKINS_URL
          value: "https://marlys-unrazored-carrie.ngrok-free.dev"
        - name: LOGSTASH_HOST
          value: "logstash"
        - name: LOGSTASH_PORT
          value: "5000"
        - name: VAULT_ADDR
          value: "http://192.168.49.1:8200"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: db-volume
          mountPath: /app/db
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: fake-news-db-pvc
